export const SEARCH_DEBOUNCE_MS = 300;
export const NICKNAME_CHECK_DEBOUNCE_MS = 500;
export const EMAIL_COOLDOWN_SECONDS = 60;
export const MANUAL_RETRY_COOLDOWN_MS = 1200;
export const ANALYSIS_POLL_INTERVAL_MS = 10000;
export const ANALYSIS_POLL_MAX_ATTEMPTS = 2;
