-- =====================================================================
-- ARTIFACT SEED — Wireframe D-03 (long-form writing, question_no 53)
-- Generated by wireframe-db-conformance fan-out (parallel). DO NOT hand-apply
-- into shared seed.sql / migrations. This is a check-only artifact (canDML=false).
--
-- SECRETS: contains NO connection credentials. Apply (if ever) only via an
-- environment that supplies the service-role connection at the moment of use.
--
-- IDEMPOTENCY: additive + deterministic. Primary id is derived from provenance
--   md5(source_file || ':' || <json item id>)::uuid
-- and the insert is guarded by WHERE NOT EXISTS on (domain='writing',
-- question_no=53), so it is a byte-identical no-op when a representative row
-- (e.g. supabase/seed.sql audit_seed 33333333-...-333) already exists. Uses
-- ON CONFLICT (id) DO NOTHING for immutable provenance (house convention).
-- NEVER reset / drop / truncate.
--
-- RECONCILED WITH PRIOR SEED: supabase/seed.sql already seeds a (writing, 53)
-- representative at fixed UUID 33333333-3333-3333-3333-333333333333
-- (tag audit_seed, source curated, materials.chart jsonb). Per the RECONCILE
-- rule this artifact does NOT add a parallel copy — the guard below skips when
-- that representative is present. reconciledWithPriorSeed = true.
--
-- PROVENANCE: source_file=docs/Wireframe/10-D-03-long-form-writing-53/sample-53.json
--             source_id (json item id)=45e8eaea-4919-4f19-b0d7-6ec0ccc319f1  (array-index fallback FORBIDDEN)
--             tags: wireframe_seed, wf:D-03
-- ITEMS AVAILABLE in sample: 62.  ROWS PLANNED: 1 (representative only).
--
-- NOT NULL columns of public.problems enumerated + CHECK-valid values supplied:
--   source='curated' (CHECK in ai_generated,curated)   domain='writing' (reading,listening,writing)
--   topik_level=2 (1,2)                                 title (no default; derived)
--   prompt (from prompt_text)                           tags (default {} -> explicit)
--   publish_status='published' (draft,published,archived)
--   review_status='approved' (pending,approved,rejected)
--   visibility='public' (private,public,org)
--   id/created_at/updated_at use column defaults.
--   difficulty=4 (CHECK 1..5 -> in range).
--   question_no=53 (CHECK in 51,52,53,54).
--   author_id left NULL (FK profiles.id ON DELETE SET NULL; user-independent seed).
--   answer_key/materials/rubric -> jsonb (nullable).
-- =====================================================================

insert into public.problems
  (id, source, author_id, domain, question_no, topik_level, difficulty,
   title, prompt, materials, answer_key, rubric, tags,
   publish_status, review_status, visibility)
select
  '3786ca18-1c47-2269-165f-2eb57279a0af'::uuid,
  'curated',
  null,
  'writing',
  53::smallint,
  2::smallint,
  4::smallint,
  'TOPIK 53번 — 청년 창업 비율(전체) / 업종별 비율 (Wireframe 예시)',
  '다음을 참고하여 200~300자로 글을 쓰시오. 단, 글의 제목은 쓰지 마시오. (30점)
1) ''청년 창업 비율(전체)''의 전체적인 경향을 쓰시오.
2) ''업종별 비율''의 항목 간 차이를 쓰시오.
3) 위의 내용을 정리하여 마무리하시오.',
  '{"charts":{"chart_a":{"chart_type":"bar","title":"청년 창업 비율(전체)","unit":"%","survey_org":"중소벤처기업부","year_range":[2024,2025,2026],"series":[{"label":"비율","values":[28,36,45]}]},"chart_b":{"chart_type":"donut","title":"업종별 비율","unit":"%","survey_org":"중소벤처기업부","year_range":[2026],"series":[{"label":"콘텐츠","values":[39]},{"label":"IT","values":[30]},{"label":"외식","values":[19]},{"label":"기타","values":[12]}]}},"chart_roles":{"chart_a_role":"overall_trend","chart_b_role":"group_detail"},"context_notes":{"display_label":"원인","row1_label":"원인","row1_value":"정부의 창업 지원 정책 확대","row2_label":"현황","row2_value":"콘텐츠와 IT 업종의 비중이 높게 나타남","cause":"정부의 창업 지원 정책 확대","status":"콘텐츠와 IT 업종의 비중이 높게 나타남"},"narrative":{"summary_trend":"청년 창업 비율은 2024년 28%에서 2026년 45%로 꾸준히 상승하였다.","detail_feature":"2026년 업종별 비율은 콘텐츠 39%, IT 30%, 외식 19%, 기타 12%로 나타났다.","rank_flip_sentence":"","cause_keywords":["창업","지원"],"cause_sentence":"정부의 창업 지원 정책 확대가 이러한 변화의 주요 원인으로 분석된다.","plan_keywords":[],"forecast_sentence":"","problem_sentence":"","solution_keywords":[],"solution_sentence":""},"relation":{"cause_label":"창업","effect_label":"창업 활성화","description":"창업 지원 확대 영향 청년 창업 활성화."},"scenario_logic":{"scenario_title":"청년 창업 비율(전체)과(와) 업종별 비율의 연결","shared_context":"창업 지원 확대 영향 청년 창업 활성화.","logic_chain":["창업","창업 지원 확대","창업 지원 확대 영향 청년 창업 활성화"],"chart_a_focus":"청년 창업 비율(전체)의 변화가 공통 상황의 출발점이다.","chart_b_focus":"업종별 비율은(는) 세부 결과를 보여 준다.","cross_chart_bridge":"청년 창업 비율(전체)에서 나타난 변화가 업종별 비율의 세부 양상으로 이어진다.","writing_reason":"수험자가 전체 변화와 세부 증거를 종합하여 서론-본론-결론 구조로 글을 작성할 수 있다."},"meta":{"domain":"경제","topic_type":"cause_effect","question_type":"type1_dual_cause","narrative_slots":["summary_trend","detail_feature","cause_keywords","cause_sentence"],"difficulty":4,"inference_gap":true,"link_keywords":["그 결과","영향"]},"__seed":{"source_file":"docs/Wireframe/10-D-03-long-form-writing-53/sample-53.json","source_id":"45e8eaea-4919-4f19-b0d7-6ec0ccc319f1"}}'::jsonb,
  '{"model_answer":"중소벤처기업부 조사에 따르면 청년 창업 비율은 2024년 28%에서 2025년 36%, 2026년 45%로 꾸준히 상승하였다. 중소벤처기업부 자료를 보면 2026년 업종별 비율은 콘텐츠 39%, IT 30%, 외식 19%, 기타 12%로 나타났다. 이처럼 콘텐츠와 IT 업종의 비중이 높게 나타난 것은 정부의 창업 지원 정책 확대에 따른 것으로 볼 수 있다.","narrative_slots":["summary_trend","detail_feature","cause_keywords","cause_sentence"]}'::jsonb,
  '{"content":"과제 3개를 모두 수행하고, 자료의 핵심 정보가 왜곡 없이 반영되었는가.","structure":"도입-전개-마무리의 흐름이 자연스럽고, 정보 배열이 논리적인가.","language":"격식체가 일관되고, 문법과 어휘 사용이 정확한가."}'::jsonb,
  ARRAY['wireframe_seed','wf:D-03']::text[],
  'published',
  'approved',
  'public'
where not exists (
  select 1 from public.problems p
  where p.domain = 'writing' and p.question_no = 53
)
on conflict (id) do nothing;

-- USER-DEPENDENT rows (writing_drafts / writing_submissions) are intentionally
-- NOT seeded here: they require an auth user uuid and must be created by a
-- separate service-role + Auth-Admin script. FOLLOW-UP, not attempted here.
