import { APP_ROUTES } from "./paths";

export type RouteMiddleware = "public" | "protected" | "excluded";
export type AppRouteType =
  | "page"
  | "system-page"
  | "route-handler"
  | "api-route";

export type AppRouteSpec = {
  id: string;
  iaCode: string;
  title: string;
  path: string;
  pathPattern?: string;
  samplePath?: string;
  appPath: string;
  routeType: AppRouteType;
  middleware: RouteMiddleware;
};

export const APP_ROUTE_SPECS: readonly AppRouteSpec[] = [
  {
    id: "landing",
    iaCode: "X-01",
    title: "제품 랜딩",
    path: APP_ROUTES.landing,
    appPath: "src/app/page.tsx",
    routeType: "page",
    middleware: "public",
  },
  {
    id: "sign-up",
    iaCode: "A-01",
    title: "회원가입",
    path: APP_ROUTES.signUp,
    appPath: "src/app/sign-up/page.tsx",
    routeType: "page",
    middleware: "public",
  },
  {
    id: "login",
    iaCode: "A-02",
    title: "로그인",
    path: APP_ROUTES.login,
    appPath: "src/app/login/page.tsx",
    routeType: "page",
    middleware: "public",
  },
  {
    id: "password-reset",
    iaCode: "X-06",
    title: "비밀번호 재설정",
    path: APP_ROUTES.passwordReset,
    appPath: "src/app/password-reset/page.tsx",
    routeType: "page",
    middleware: "public",
  },
  {
    id: "password-reset-confirm",
    iaCode: "X-16",
    title: "새 비밀번호 설정",
    path: APP_ROUTES.passwordResetConfirm,
    appPath: "src/app/password-reset/confirm/page.tsx",
    routeType: "page",
    middleware: "public",
  },
  {
    id: "auth-callback",
    iaCode: "AUTH-CALLBACK",
    title: "인증 콜백 라우트 핸들러",
    path: APP_ROUTES.authCallback,
    appPath: "src/app/auth/callback/route.ts",
    routeType: "route-handler",
    middleware: "public",
  },
  {
    id: "auth-callback-fragment",
    iaCode: "X-17",
    title: "인증 콜백 fragment 처리",
    path: APP_ROUTES.authCallbackFragment,
    appPath: "src/app/auth/callback-fragment/page.tsx",
    routeType: "page",
    middleware: "public",
  },
  {
    id: "auth-error",
    iaCode: "X-11",
    title: "인증 에러",
    path: APP_ROUTES.authError,
    appPath: "src/app/auth/error/page.tsx",
    routeType: "page",
    middleware: "public",
  },
  {
    id: "auth-verify-email",
    iaCode: "X-12",
    title: "인증 메일 확인 안내",
    path: APP_ROUTES.authVerifyEmail,
    appPath: "src/app/auth/verify-email/page.tsx",
    routeType: "page",
    middleware: "public",
  },
  {
    id: "auth-sign-out",
    iaCode: "AUTH-SIGN-OUT",
    title: "로그아웃 라우트 핸들러",
    path: APP_ROUTES.authSignOut,
    appPath: "src/app/auth/sign-out/route.ts",
    routeType: "route-handler",
    middleware: "public",
  },
  {
    id: "terms",
    iaCode: "X-13",
    title: "이용약관",
    path: APP_ROUTES.terms,
    appPath: "src/app/terms/page.tsx",
    routeType: "page",
    middleware: "public",
  },
  {
    // 약관 변경 알림 이메일 CTA용 공개 진입점. 로그인 세션이 있으면 /auth/consent
    // 로, 없으면 /login?next=/auth/consent 로 보내 로그인 후 동의 화면으로 잇는다.
    id: "terms-agreement",
    iaCode: "X-13B",
    title: "약관 재동의 진입",
    path: APP_ROUTES.termsAgreement,
    appPath: "src/app/terms-agreement/page.tsx",
    routeType: "page",
    middleware: "public",
  },
  {
    id: "privacy",
    iaCode: "X-14",
    title: "개인정보처리방침",
    path: APP_ROUTES.privacy,
    appPath: "src/app/privacy/page.tsx",
    routeType: "page",
    middleware: "public",
  },
  {
    id: "auth-post-auth",
    iaCode: "AUTH-POST",
    title: "OAuth 후처리",
    path: APP_ROUTES.authPostAuth,
    appPath: "src/app/auth/post-auth/page.tsx",
    routeType: "system-page",
    middleware: "protected",
  },
  {
    id: "auth-consent",
    iaCode: "X-18",
    title: "소셜 로그인 약관 동의",
    path: APP_ROUTES.authConsent,
    appPath: "src/app/auth/consent/page.tsx",
    routeType: "page",
    middleware: "protected",
  },
  {
    id: "dashboard",
    iaCode: "B-01",
    title: "홈 대시보드",
    path: APP_ROUTES.dashboard,
    appPath: "src/app/(workspace)/dashboard/page.tsx",
    routeType: "page",
    middleware: "protected",
  },
  {
    id: "growth",
    iaCode: "X-02",
    title: "성장 대시보드",
    path: APP_ROUTES.growth,
    appPath: "src/app/(workspace)/growth/page.tsx",
    routeType: "page",
    middleware: "protected",
  },
  {
    id: "library",
    iaCode: "F-01",
    title: "내 서재",
    path: APP_ROUTES.library,
    appPath: "src/app/(workspace)/library/page.tsx",
    routeType: "page",
    middleware: "protected",
  },
  {
    id: "library-problems",
    iaCode: "F-01-PROBLEMS",
    title: "Library saved problems all view",
    path: APP_ROUTES.libraryProblems,
    appPath: "src/app/(workspace)/library/problems/page.tsx",
    routeType: "page",
    middleware: "protected",
  },
  {
    id: "profile",
    iaCode: "X-05",
    title: "프로필 편집",
    path: APP_ROUTES.profile,
    appPath: "src/app/(workspace)/profile/page.tsx",
    routeType: "page",
    middleware: "protected",
  },
  {
    id: "settings-learning",
    iaCode: "SETTINGS-LEARNING",
    title: "Learning goal settings",
    path: APP_ROUTES.settingsLearning,
    appPath: "src/app/(workspace)/settings/learning/page.tsx",
    routeType: "page",
    middleware: "protected",
  },
  {
    id: "settings-account",
    iaCode: "SETTINGS-ACCOUNT",
    title: "Account settings",
    path: APP_ROUTES.settingsAccount,
    appPath: "src/app/(workspace)/settings/account/page.tsx",
    routeType: "page",
    middleware: "protected",
  },
  {
    id: "settings-language",
    iaCode: "G-01",
    title: "설정 언어",
    path: APP_ROUTES.settingsLanguage,
    appPath: "src/app/(workspace)/settings/language/page.tsx",
    routeType: "page",
    middleware: "protected",
  },
  {
    id: "settings-notifications",
    iaCode: "X-09",
    title: "알림 설정",
    path: APP_ROUTES.settingsNotifications,
    appPath: "src/app/(workspace)/settings/notifications/page.tsx",
    routeType: "page",
    middleware: "protected",
  },
  {
    id: "practice-recommendations",
    iaCode: "C-01",
    title: "문제 유형 추천",
    path: APP_ROUTES.practiceRecommendations,
    appPath: "src/app/(workspace)/practice/recommendations/page.tsx",
    routeType: "page",
    middleware: "protected",
  },
  {
    id: "practice-problems",
    iaCode: "C-02",
    title: "문제 목록",
    path: APP_ROUTES.practiceProblems,
    appPath: "src/app/(workspace)/practice/problems/page.tsx",
    routeType: "page",
    middleware: "protected",
  },
  {
    id: "practice-next",
    iaCode: "R-02",
    title: "다음 문제 추천",
    path: APP_ROUTES.practiceNext,
    appPath: "src/app/(workspace)/practice/next/page.tsx",
    routeType: "page",
    middleware: "protected",
  },
  {
    id: "practice-weakness",
    iaCode: "X-07",
    title: "약점 기반 추천",
    path: APP_ROUTES.practiceWeakness,
    appPath: "src/app/(workspace)/practice/weakness/page.tsx",
    routeType: "page",
    middleware: "protected",
  },
  {
    id: "writing-51",
    iaCode: "D-01",
    title: "51번 단답 작성",
    path: APP_ROUTES.writing51,
    appPath: "src/app/(workspace)/writing/short-answer-writing-51/page.tsx",
    routeType: "page",
    middleware: "protected",
  },
  {
    id: "writing-52",
    iaCode: "D-02",
    title: "52번 답안 작성",
    path: APP_ROUTES.writing52,
    appPath: "src/app/(workspace)/writing/answer-writing-52/page.tsx",
    routeType: "page",
    middleware: "protected",
  },
  {
    id: "writing-53",
    iaCode: "D-03",
    title: "53번 장문 작성",
    path: APP_ROUTES.writing53,
    appPath: "src/app/(workspace)/writing/long-form-writing-53/page.tsx",
    routeType: "page",
    middleware: "protected",
  },
  {
    id: "writing-54",
    iaCode: "D-04",
    title: "54번 에세이 작성",
    path: APP_ROUTES.writing54,
    appPath: "src/app/(workspace)/writing/essay-writing-54/page.tsx",
    routeType: "page",
    middleware: "protected",
  },
  {
    id: "feedback-short",
    iaCode: "E-01",
    title: "단답 피드백",
    path: APP_ROUTES.feedbackShort,
    pathPattern: APP_ROUTES.feedbackShort,
    samplePath: "/writing/feedback/short/abc-id",
    appPath: "src/app/(workspace)/writing/feedback/short/[id]/page.tsx",
    routeType: "page",
    middleware: "protected",
  },
  {
    id: "feedback-long",
    iaCode: "E-02",
    title: "장문 피드백",
    path: APP_ROUTES.feedbackLong,
    pathPattern: APP_ROUTES.feedbackLong,
    samplePath: "/writing/feedback/long/abc-id",
    appPath: "src/app/(workspace)/writing/feedback/long/[id]/page.tsx",
    routeType: "page",
    middleware: "protected",
  },
  {
    id: "comparison-report",
    iaCode: "R-01",
    title: "비교 리포트",
    path: APP_ROUTES.comparisonReport,
    pathPattern: APP_ROUTES.comparisonReport,
    samplePath: "/writing/reports/abc-id/compare",
    appPath: "src/app/(workspace)/writing/reports/[id]/compare/page.tsx",
    routeType: "page",
    middleware: "protected",
  },
  {
    id: "learning-goal",
    iaCode: "A-03",
    title: "학습 목표 설정",
    path: APP_ROUTES.onboardingLearningGoal,
    appPath: "src/app/(workspace)/onboarding/learning-goal/page.tsx",
    routeType: "page",
    middleware: "protected",
  },
  {
    id: "subscription",
    iaCode: "X-04",
    title: "구독 관리",
    path: APP_ROUTES.subscription,
    appPath: "src/app/(workspace)/subscription/page.tsx",
    routeType: "page",
    middleware: "protected",
  },
  {
    id: "paywall",
    iaCode: "X-03",
    title: "페이월",
    path: APP_ROUTES.paywall,
    appPath: "src/app/(workspace)/paywall/page.tsx",
    routeType: "page",
    middleware: "protected",
  },
  {
    id: "api-system-reports",
    iaCode: "API-SYSTEM-REPORTS",
    title: "System report submission API",
    path: APP_ROUTES.apiSystemReports,
    appPath: "src/app/api/system-reports/route.ts",
    routeType: "api-route",
    middleware: "excluded",
  },
  {
    id: "api-export-pdf",
    iaCode: "API-EXPORT-PDF",
    title: "PDF 내보내기 API",
    path: APP_ROUTES.apiExportPdf,
    appPath: "src/app/api/export/pdf/route.ts",
    routeType: "api-route",
    middleware: "excluded",
  },
  {
    id: "api-notifications-dispatch-email",
    iaCode: "API-NOTIFICATIONS-DISPATCH-EMAIL",
    title: "알림 이메일 발송 API",
    path: APP_ROUTES.apiNotificationsDispatchEmail,
    appPath: "src/app/api/notifications/dispatch-email/route.ts",
    routeType: "api-route",
    middleware: "excluded",
  },
  {
    id: "api-notifications-unsubscribe",
    iaCode: "API-NOTIFICATIONS-UNSUBSCRIBE",
    title: "알림 수신거부 API",
    path: APP_ROUTES.apiNotificationsUnsubscribe,
    appPath: "src/app/api/notifications/unsubscribe/route.ts",
    routeType: "api-route",
    middleware: "excluded",
  },
] as const;

export const PUBLIC_PATHS = APP_ROUTE_SPECS.filter(
  (route) => route.middleware === "public",
).map((route) => route.path);

export type ProtectedRouteCase = {
  path: string;
  iaCode: string;
};

export const PROTECTED_ROUTE_CASES: readonly ProtectedRouteCase[] =
  APP_ROUTE_SPECS.filter((route) => route.middleware === "protected").map(
    (route) => ({
      path: route.samplePath ?? route.path,
      iaCode: route.iaCode,
    }),
  );
