export const APP_ROUTES = {
  landing: "/",
  signUp: "/sign-up",
  login: "/login",
  passwordReset: "/password-reset",
  passwordResetConfirm: "/password-reset/confirm",
  authCallback: "/auth/callback",
  authCallbackFragment: "/auth/callback-fragment",
  authError: "/auth/error",
  authVerifyEmail: "/auth/verify-email",
  authPostAuth: "/auth/post-auth",
  authConsent: "/auth/consent",
  authSignOut: "/auth/sign-out",
  authAccountInactive: "/auth/account-inactive",
  authAccountDelete: "/auth/account-delete",
  terms: "/terms",
  termsAgreement: "/terms-agreement",
  privacy: "/privacy",
  onboardingLearningGoal: "/onboarding/learning-goal",
  dashboard: "/dashboard",
  practiceRecommendations: "/practice/recommendations",
  practiceProblems: "/practice/problems",
  practiceNext: "/practice/next",
  practiceWeakness: "/practice/weakness",
  writing51: "/writing/short-answer-writing-51",
  writing52: "/writing/answer-writing-52",
  writing53: "/writing/long-form-writing-53",
  writing54: "/writing/essay-writing-54",
  feedbackShort: "/writing/feedback/short/:id",
  feedbackLong: "/writing/feedback/long/:id",
  comparisonReport: "/writing/reports/:id/compare",
  library: "/library",
  libraryProblems: "/library/problems",
  growth: "/growth",
  paywall: "/paywall",
  subscription: "/subscription",
  profile: "/profile",
  settingsLearning: "/settings/learning",
  settingsAccount: "/settings/account",
  settingsLanguage: "/settings/language",
  settingsNotifications: "/settings/notifications",
  apiSystemReports: "/api/system-reports",
  apiExportPdf: "/api/export/pdf",
  apiNotificationsDispatchEmail: "/api/notifications/dispatch-email",
  apiNotificationsUnsubscribe: "/api/notifications/unsubscribe",
} as const;

export const WRITING_ROUTE_SEGMENTS_BY_QUESTION = {
  51: "short-answer-writing-51",
  52: "answer-writing-52",
  53: "long-form-writing-53",
  54: "essay-writing-54",
} as const;

export const WRITING_ROUTE_PATHS_BY_QUESTION = {
  51: APP_ROUTES.writing51,
  52: APP_ROUTES.writing52,
  53: APP_ROUTES.writing53,
  54: APP_ROUTES.writing54,
} as const;

export const AUTH_ENTRY_PATHS = [APP_ROUTES.login, APP_ROUTES.signUp] as const;
